[package]
name = "geojson-vt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"
geozero = "0.13.0"
euclid = "0.22.10"
